#!/usr/bin/env bash


 # ██████╗  ███████╗ ██████╗  ██╗    ██╗ ███╗   ███╗
 # ██╔══██╗ ██╔════╝ ██╔══██╗ ██║    ██║ ████╗ ████║
 # ██████╔╝ ███████╗ ██████╔╝ ██║ █╗ ██║ ██╔████╔██║
 # ██╔══██╗ ╚════██║ ██╔═══╝  ██║███╗██║ ██║╚██╔╝██║
 # ██████╔╝ ███████║ ██║      ╚███╔███╔╝ ██║ ╚═╝ ██║
 # ╚═════╝  ╚══════╝ ╚═╝       ╚══╝╚══╝  ╚═╝     ╚═╝

## important variables

read -r RICETHEME <"$HOME"/.config/bspwm/scripts/.rice
export RICETHEME
PATH="$HOME/.config/bspwm/scripts:$PATH"
rice_dir="$HOME/.config/bspwm/rices/$RICETHEME"

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1
export JDK_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# setup connected monitors #
NUM_OF_MONITORS=$(xrandr --listmonitors | grep -c "^ ") # No. monitors #

if [[ ${NUM_OF_MONITORS} -ge 1 ]]; then
	"$HOME/.config/bspwm/scripts/display-inoutput/multimonitor"
fi

## workspace
workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' ''
		((name++))
	done
}

workspaces

# Set refresh rate to 50Hz
xrandr --rate 50 &

bspc config border_radius 8
bspc config border_width 4
bspc config window_gap 10
bspc config top_padding 20
bspc config bottom_padding 20
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle false
bspc config click_to_focus true
bspc config history_aware_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_verlapping_monitors true

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config split_ratio 0.50

# Windows Border Settings
bspc config focused_border_color "#3888A0"
bspc config normal_border_color "#D4D4D4"
bspc config active_border_color "#073642"

bspc config inactive_border_color "#24BEB0"
bspc config normal_border_color "#5D6ADE"
bspc config active_border_color "#5D1CE6"

### Secondary Monitor Setup
bspc config -m 2 top_padding 3
bspc config -m 2 bottom_padding 3
bspc config -m 2 right_padding 3
bspc config -m 2 left_padding 3

### Launching Rices

# Set system vars for polybar
. "$HOME/.config/bspwm/scripts/SetSysVars"

# Terminate already running polybar, eww, picom, sxhkd and dunst instances
processes=("picom" "polybar" "eww" "sxhkd" "dunst")

for process in "${processes[@]}"; do
	if pidof -q "$process"; then
		pkill -9 -x "$process" >/dev/null
		sleep 0.1
	fi
done

# Load colors, dunst, bars and/or eww widgets
. ${rice_dir}/Theme.sh

# Launch picom // If you have old hardware or encounter problems
# uncomment the picom "--legacy-backends" line and comment the current one.
picom --config "$HOME/.config/picom/picom.conf" &
#picom --legacy-backends --config "$HOME"/.config/bspwm/picom.conf &

# Launch dunst notification daemon
dunst -config "$HOME"/.config/bspwm/dunstrc &

# Set random wallpaper for actual rice
feh -z --no-fehbg --bg-fill ${rice_dir}/walls
#feh --no-fehbg --bg-fill path-to-your-png

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor
xsetroot -cursor_name left_ptr
