#!/usr/bin/env bash

export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

INTERNAL_MONITOR="DP-0"
EXTERNAL_MONITOR=$(~/.config/bspwm/scripts/getExternalMonitor -i $INTERNAL_MONITOR)

if [[ "$1" = 0 ]]; then
	if xrandr -q | grep "${EXTERNAL_MONITOR} connected"; then
		xrandr --output ${EXTERNAL_MONITOR} --mode 1366x768 --above ${INTERNAL_MONITOR}
		bspc monitor "${EXTERNAL_MONITOR}" -d one two three four five
		bspc monitor "${INTERNAL_MONITOR}" -d six seven eight nine ten
		bspc wm -O "${EXTERNAL_MONITOR}" "$INTERNAL_MONITOR"

	else
		bspc monitor "${INTERNAL_MONITOR}" -d one two three four five six seven eight nine ten
	fi
fi

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
	~/.config/bspwm/scripts/monitorAdd -i $INTERNAL_MONITOR -e $EXTERNAL_MONITOR
else
	if [[ $(bspc query -M | wc -l) -eq 2 ]]; then
		~/.config/bspwm/scripts/monitorRemove -i $INTERNAL_MONITOR -e $EXTERNAL_MONITOR
	fi
fi

pgrep -x sxhkd >/dev/null || sxhkd &

. "$HOME/.screenlayout/screen-layout.sh" &

picom --config $HOME/.config/picom/picom.conf -b &

nitrogen --restore --zoom-fill "$HOME/Pictures/WallPapers/wallhaven-eyd1ek.png" &

. $HOME/.config/polybar/launch.sh --shapes &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 5
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config split_ratio 0.50

# Windows Border Settings
bspc config focused_border_color "#3888A0"
bspc config normal_border_color "#D4D4D4"
bspc config active_border_color "#073642"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
_border_color "#24BEB0"
bspc config normal_border_color "#5D6ADE"
bspc config active_border_color "#5D1CE6"
