<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>varlink</string>
	</array>
	<key>name</key>
	<string>varlink</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^\s+)?(?&lt;=^|\W)(?=#)(?!#{)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.varlink</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.varlink</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.number-sign.varlink</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(method)\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.function.varlink</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=[(])</string>
			<key>name</key>
			<string>meta.method.declaration.varlink</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.varlink</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([A-Z][a-zA-Z0-9_]*)\b</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|\s)(interface|type|error)(?=\s|$)</string>
			<key>name</key>
			<string>keyword.other.varlink</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>end</key>
			<string>[(),]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(string|bool|int|float|object)\b</string>
					<key>name</key>
					<string>storage.type.varlink</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\[\]|\[string\]|\?)</string>
					<key>name</key>
					<string>storage.modifier.varlink</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Z][a-zA-Z0-9_]*)\b</string>
			<key>name</key>
			<string>entity.name.type.varlink</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.varlink</string>
	<key>uuid</key>
	<string>79A82AF6-18BA-4FB5-ACE0-5CBE036351A8</string>
</dict>
</plist>
