version: 2

jobs:
  build-linux:
    docker:
      - image: circleci/python
    environment:
      PACKAGE: "Terraform" # Package name
      SUBLIME_TEXT_VERSION: "3"
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install libglib2.0-0 libgtk-3-0
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/circleci.sh
      - run: |
          export DISPLAY=:99.0
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          PATH="$HOME/.local/bin:$PATH"

          # bootstrap the testing environment
          sh circleci.sh bootstrap

          # install Package Control and package denepdencies
          # sh circleci.sh install_package_control

          # run tests with test coverage report
          sh circleci.sh run_tests --coverage

          # testing syntax_test files
          # - sh travis.sh run_syntax_tests
      - run: |
          sudo pip install codecov
          codecov

  # build-macos:
  #   macos:
  #     xcode: "9.0"
  #   environment:
  #     PACKAGE: "UnitTesting-example"  # Package name
  #     SUBLIME_TEXT_VERSION: "3"
  #   steps:
  #     - checkout
  #     - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/circleci.sh
  #     - run: |
  #         export PATH="$HOME/.local/bin:$PATH"
  #         # bootstrap the testing environment
  #         sh circleci.sh bootstrap
  #         # install Package Control and package denepdencies
  #         # sh circleci.sh install_package_control
  #         # run tests with test coverage report
  #         sh circleci.sh run_tests --coverage
  #         # testing syntax_test files
  #         # - sh travis.sh run_syntax_tests
  #     - run: |
  #         brew upgrade python
  #         pip3 install codecov
  #         codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-linux
      # - build-macos
